# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShapefileCreator
                                 A QGIS plugin
 Create new shapefile from existing shapefile
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-09
        copyright            : (C) 2019 by Arun Kumar M
        email                : marunkumar664@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ShapefileCreator class from file ShapefileCreator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .create_shapefile import ShapefileCreator
    return ShapefileCreator(iface)
